### ISSUE TITLE
Broken pipe with .stop_recording() on closed connection when streaming to VLC webpage plugin

### ISSUE THREAD

**Issue by guardrex** [waveform80/picamera#122]
Hi Dave,

Thanks for adding the recipe for using PiCamera as a streaming server where the Pi waits for a connection (e.g., a webpage with a VLC plugin on it) and then starts streaming to the plugin (the last example of Recipe 4.12). It works great! I was able to shed that horrid Raspivid-to-VLC method that I was using to stream video with the even more horrible process-killing code to stop the Raspivid streaming ... yuck! I also have the bonus that I can snap images while recording now. Three cheers for Dave!

However, one issue has come up that might be a bug (or maybe it's me being an idiot ... that happens a lot, too): If the webpage is closed (or in my case the connection is dropped because the VLC webpage plugin is disabled, shutdown, or hidden on the client-side), PiCamera will choke **later** on a broken pipe exception when the `.stop_recording()` method is called.

Here's the code scenario:

Early in program execution, setup a camera:

```
camera = picamera.PiCamera()
camera.resolution = (320, 240)
```

During execution at some point, we need some streaming, e.g., the website visitor has clicked a button to command streaming to start (I handle this with a http.server in a separate thread):

```
pi_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
pi_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
pi_socket.bind(('0.0.0.0', 8080))
pi_socket.settimeout(5.0)
pi_socket.listen(0)
conn = pi_socket.accept()[0].makefile('wb')
camera.framerate = 24
camera.start_recording(conn, format='h264', quality=25)
```

Later, code is called to kill the streaming, e.g., when the website visitor has clicked a button to command the streaming to stop or when a pre-established timeout has been specified to kill the streaming at some point ... a ten minute timer for example:

```
camera.stop_recording()
camera.close()
conn.close()
pi_socket.close()
```

btw - You have two recipes that call for the camera to `.close()` in different places (using `with` blocks). One recipe shows it called prior to the connection closing, while the other has it called after the connection is closed. It doesn't seem to make a difference, nor does it really factor into this issue I'm describing.

Here's what happens: The streaming is started. At some point during streaming, the user closes their browser window or the VLC webpage plugin is shutdown. Nothing happens at that point. No exceptions are thrown, and nothing obvious happens with the camera object or the connection. Later, when the last bit of code runs to kill the streaming (because server-side, we don't know that the client has stopped receiving the stream and killed the connection), we get an `[Errno 32] Broken pipe` when the `.stop_recording()` is called.

I sort of wonder if this is a bug (or an unintended consequence of the way things work between PiCamera and the connection). I wrap my `.stop_recording()` in a `try-except` block as a work-around. However, if PiCamera senses a broken pipe when its trying to wrap up the streaming, shouldn't it just exit the method gracefully without an exception? ... thinking 'the connection must have closed at some point ... oh, well ... no big deal.'

Thanks again for all you're doing with PiCamera. It's one the best API's that I've **ever** used on **any** platform!

**Comment by matmicro** [comment]
Hi, 
I am using this library from many years now without any issue.
I moved to raspberry pi camera HQ, and i am now facing sometimes a Broken Pipe exception.

Any idea what could cause that ?
The file recorded is 0 bytes.

What could be the root cause ?
How should i fix that ?

Thanks and regards
