### ISSUE TITLE
Image capture during video capture question

### ISSUE THREAD

**Issue by GuardRex** [waveform80/picamera#125]
Hello Dave,

The Encoders section and recipes don't quite match what I'm trying to accomplish. I want to snap high quality images at high resolution with the still port while capturing lower resolution video from the video port. I don't care about dropped frames if a mode change is needed as long as the video capture isn't killed. I've tried to accomplish this by doing the following:

Set the camera resolution to 320x240
Start video capture
Snap image with resize=2592x1944 using video_port=False

Problem: Judging by the poor quality of the image taken, the use of resize seems to be resizing a capture at the camera resolution of 320x240 to 2592x1944 ... not actually taking the still image at 2592x1944.

If I flip this and hit it the other way ...

Set the camera resolution to 2592x1944
Start video capture with resize=320x240
Snap image using video_port = False

Problems: (1) Many dropped frames in the video (even when I'm not calling for a `.capture()` image), (2) When I attempt to snap the image, it throws an exception: "Recording is currently running."

So far, it seems that the only way to do something like this (along the lines of my first attempt) would be to capture video at high resolution (>=1292x730) so that the resize with `.capture()` will not result in a great loss of image quality. Is that the only way to pull this off?

**Comment by bennettrogers** [comment]
Sorry for reviving an old thread, but I'm trying to do something very similar to this and I wondered what your eventual solution was? @GuardRex how did you end up capturing and storing high quality images? I am able to stream h264 video and simultaneously capture YUV images on the still port, but I can't figure out how to do anything useful with the YUV files. Ideally there would be a fast (GPU accelerated?) way to jpeg encode them before storage, but if I need to post-process them I think that would be ok.

Thanks for any insight you can share!

**Comment by GuardRex** [comment]
@bennettrogers I ended up just snapping the image from the still port while using MJPEG streaming. This ended up meeting my needs the best: For my system, the quality of the video is **not** all that important ... the high-res image snaps are more important.

By setting up a MJPEG stream, I'm able to keep everything (streaming video and hi-res image snaps) all in an image-snapping scenario without having to jump back and forth between H.264 and snapping images or without degrading the H.264 too much due to camera mode changes while snapping images.

For the MJPEG streaming, I'm using JPEG image snaps (of course), the video port of the camera, a quality setting of 10, no thumbnail, and a res of 320x240. No matter if the MJPEG is actively streaming or not, I can jump in anytime and take a hi-res snap ... a JPEG, using the still port, a quality setting of 85, thumbnail with it, and at full camera resolution 2592x1944. It works pretty well.

As the for the specifics on captures (hi-res images), I just take JPEG's from the camera into a io.BytesIO object. I use PIL for image mods prior to saving the snaps. I can't really say anything here (publicly) about how the MJPEG stream works or what happens with the snaps for security reasons, but  you can find many good resources online that will help you stream MJPEG off the Pi. Then, you can just snap hi-res as you go.

**Comment by bennettrogers** [comment]
Thanks for the reply. What framerate are you getting for the mjpeg stream? The quality of the stills is more important in my scenario as well, but I would love to get the stream to be of reasonable quality. A quick test was getting me only 2-3fps (vs at least 25fps for h.264), but I haven't tried tweaking the settings much yet. If I can play around enough to figure out a configuration that will give me a decent video stream, this might end up being sufficient. I tested the approach of using the video port to capture the stills, and the loss of FOV and metadata wasn't acceptable.

@waveform80, if I stick to the route of h.264 streaming and capturing raw stills, do you have any thoughts on the most efficient way to encode the YUV images into jpeg? I imagine I could figure out something with the PiYUVArray, but that sounds resource intensive if done naively (which is probably what would happen since I'm new to this stuff). Is there a way to add a step to the pipeline to encode to jpeg with the GPU?

**Comment by GuardRex** [comment]
@bennettrogers I'm not sure on the framerate. I don't set a header coming through with it from picamera, and I can't seem to get it from Fiddler or Google Dev Tools.

**Comment by waveform80** [comment]
@bennettrogers - just trying to clear out some old tickets and realized I never replied to this, sorry!

With an MJPEG video recording you ought to get similar framerates to H264 - i.e. 25fps should be no problem. Incidentally, this isn't a matter of taking JPEGs one after another, I simply mean call `start_recording` with *format* set to `mjpeg`. You can split frames out of the result by looking for the JPEG magic sequence (ff d8). Here's some [gists to play around with](https://gist.github.com/waveform80/263b9c8bdcb1e9b79749).

**Comment by weijian19391** [comment]
@waveform80 Realised that the default example uses 
````camera.start_recording('video.h264', resize=(320, 240))
camera.wait_recording(10)
camera.capture('foo.data', 'yuv')
camera.wait_recording(10)````

In this case the response time for an image capture is 10s (if let's say i'm trigger the capture function based on some condition). To reduce the response time, one would need to decrease the parameter in `wait_recording` , is the only way to reduce the response time?

**Comment by waveform80** [comment]
The wait_recording is simply there as a demonstration - it's not required. Eliminate it entirely if you want (`wait_recording` is purely an alternative to `sleep` for providing timed delays but with one important addition: it terminates immediately if something goes wrong in the recording, like running out of disk space).
