### ISSUE TITLE
Image Comparison Question

### ISSUE THREAD

**Issue by GuardRex** [waveform80/picamera#150]
Dave,

Got another one for you. This one is really going to show my ignorance on the subject of image processing.

I would like to do a simple image comparison between two images of the same format and resolution. I don't want to try to compare every pixel between two images. I just want to be able to hit a subset of the data, get a percent difference (or something like that) at each tested pixel location, then use those pixel differences to get a crude image difference value. The scale is not particularly important, but something like a percent difference (0-1, 0%-100%) would be great.

The easy approach for a know-nothing-about-image-processing person like myself is to take the two image streams (as `io.BytesIO` objects) and convert them into images with PIL, then I can do my pixel-to-pixel comparisons [`img.getpixel(xy)` method or `img.getdata()` and checking same positions in each sequence from that method]. Once I have the differences at each spot I'm testing, I can get the average difference for the two images. Crude, yes, but that's fine. Speed is more important than accuracy or precision. This image difference value is for screening purposes so that the app can alert the user to the potential that something significant has changed between two images.

Any tips or advice on this one? What would you do for a crude (fast) image comparison function?

**Comment by waveform80** [comment]
Hi Luke,

Sorry it's taken me so long to get back to this! I think this is the same issue as #189 which I'm currently looking at (I'm slowly working through the picamera backlog, trying to clear things up for 1.10!). I'm not sure what's going on there at the moment.

A workaround you can use in your own code is to resize everything (even when it's not needed):

```python
import picamera
import numpy as np
import io
import time

camera = picamera.PiCamera()

try:
    camera.resolution = (2592, 1944)
    camera.framerate = 15
    camera.start_preview(alpha=192)
    capture_res = (52, 39)

    print('Taking Motion Detection Image (Initial)')
    stream = io.BytesIO()
    camera.capture(stream, 'yuv', resize=capture_res)
    prev_seq = np.fromstring(stream.getvalue(), dtype=np.int8)

    while True:

        time.sleep(2)

        # Images taken for MJPEG streaming
        print('Taking MJPEG Image')
        streamImg = io.BytesIO()
        camera.capture(streamImg, 'jpeg', use_video_port=True, quality=10, resize=(2592, 1944))

        # Images taken for storage/viewing
        print('Taking Storage/Viewing Image')
        io_stream = io.BytesIO()
        camera.capture(io_stream, 'jpeg', resize=(2592, 1944))

        # Images taken for motion detection
        print('Taking Motion Detection Image (Current)')
        stream = io.BytesIO()
        camera.capture(stream, 'yuv', resize=capture_res)
        curr_seq = np.fromstring(stream.getvalue(), dtype=np.int8)
        d = np.mean(abs(curr_seq - prev_seq) / 255)
        prev_seq = curr_seq

finally:
    camera.close()
```

That runs for a few loops on my test Pi (haven't run it long term so I'm not sure about its overall reliability)!

**Comment by GuardRex** [comment]
Thanks Dave!

Alas, my dev Pi is in a storage box under the bed!!! I just moved. I'll pull that out today.

Up until now, I've been using the workaround I mentioned by closing the camera and getting a new one ... very tedious (for the Pi)! I'll definitely give your code a shot today and post back my results.

**Comment by GuardRex** [comment]
Yes! That works. I was able to eliminate having to `.close()` and reacquire a camera object at that spot where I was taking a motion detection image by setting a `resize=(x,y)` on all of my `camera.capture()` calls throughout the app, whether they needed them or not.

I'll close this one and keep an eye on #189 going forward for any future updates. Thanks again!
