### ISSUE TITLE
Exposure mode problem

### ISSUE THREAD

**Issue by anacierdem** [waveform80/picamera#171]
When "exposure_mode" is set to 'off', the output is black. pi firmware and python libraries are up to date.
The pi is a model B.

Will be further investigating the issue today. I'm suspecting that the problem may be in my code.

Figured it out, setting the exposure_mode to 'off' just after setting shutter_speed results in a black image but doing;

camera.shutter_speed = 30000

time.sleep(2);

camera.exposure_mode = 'off'

solves the problem. This should be further investigated.

**Comment by waveform80** [comment]
Looks like #171 and #182 are basically the same thing: the camera's analog gain starts off (just after init) as a really low value (1) which causes all frames to return black (there's probably some good reason for doing this, but I don't know enough about the firmware to know what). If you set `exposure_mode` to "off" (fixing the gains) before auto-gain control has had a chance to raise the gain up to a reasonable level (like 8) you'll just wind up with black frame after black frame.

I'll update the docs and recipes to include information about explicitly waiting for analog gain to reach a sensible level before setting `exposure_mode` to "off".
