### ISSUE TITLE
jpeg encoding via mmal

### ISSUE THREAD

**Issue by previ** [waveform80/picamera#181]
I am developing a project that requires to implement the following video pipeline:
capture("bgr", video_port) => opencv processing => mjpeg encoding => mjpeg streaming over http
I am using [this approach](http://picamera.readthedocs.org/en/release-1.8/recipes2.html#rapid-capture-and-processing) from the docs, performing the jpeg encoding via cv2.imencode.
It works but the imencode phase is rather slow (about 2 fps @640x480)

Is it possible to perform the mjpeg encoding in hardware (MMAL)?

Or, with a different approach, is it possibile to activate a splitter and divide the pipeline as follows:
1.capture("bgr", video_port) => opencv processing
2.capture("jpeg", video_port) mjpeg streaming over http

Best regards
Roberto

**Comment by waveform80** [comment]
@previ - sorry, I forgot to respond to your question about the speed of PiYUVArray! I suspect the reason it's slower is that PiYUVArray does a little bit more than simply converting to a numpy array. In order to keep the interface as simple as possible for users, it also resizes the UV components so that they're the same size as the Y component by doubling the horizontal and vertical resolution of those planes. That's probably the cause of the slow down (I would expect the numpy conversion itself is trivial and about as fast as writing straight to BufferIO, but I haven't confirmed this)

**Comment by previ** [comment]
No problem!

Thanks a lot for the support, performance are quite good.

Just another question: I am currently using the picamera lib to capture
three streams via splitters/encoders, with a configured framerate of 30 fps:
1.jpeg for http mjpeg streaming, continuous
2.bgr fot opencv processing, continuous
3.h264 for video recording (user activated)

I found that with the three streams active, the h264 file is actually only
11-12fps, I guess this happens because the gpu cannot sustain the requested
30 frames per seconds, right?

Thanks
Roberto

**Comment by waveform80** [comment]
Hmm, I'm not entirely sure but my hunch would be that you're running into bandwidth issues. The BGR stream in particular will be sucking up a *lot* of bandwidth from GPU->CPU simply from the size of the data involved which will limit what's available for everything else. In other words, my hunch would be the GPU's got enough power to manage the work but gets bogged down waiting for all that data to get transferred to the CPU. It might be interesting to see what happened with, say, three H.264 streams vs three JPEG streams vs three BGR streams, etc. After all BGR should require almost no processing, but lots of bandwidth, and vice versa for H.264.

There may also be some interplay between the MJPEG encoder and H.264 encoder (to hear the firmware devs tell it, the H.264 encoder is well written, but the MJPEG one isn't; using it in conjunction with other things may have some interesting effects!).

**Comment by previ** [comment]
Interesting. I already did some tests and it seems the JPEG stream is the
limiting one. The bgr stream gets a resize to a tiny 160x120 pixels, that's
still good enough for opencv processing.
In the current implementation, I am using the JPEG stills to create a very
basic MJPEG stream through HTTP (a python mini http server which push a
sequence of JPEGs to the web client); an MJPEG or H264 HTTP streaming
solution would be better but I could not find anything easy to integrate
with the rest of the python code.

Roberto
