### ISSUE TITLE
Black image when exposure mode set to "off"

### ISSUE THREAD

**Issue by snoygues** [waveform80/picamera#182]
Hi use following "capture_continuous" command with 'yuv' format.

In that case, which of following parameters are active and how they change the result : 
* iso,
* awb_mode,
 * exposure_mode,
 * exposure-compensation,
 * awb_gain,
 * analog_gain,
 * brightness,
 * contrast,
 * digital_gain,
 * saturation,
 * sharpness.
I try many combinations, but it seems I get always same result...

Actually, I just need to fix all aquisition parameters, but I didn't succeded
For example, I spcecify:
        self.__Camera.iso = 800
        self.__Camera.awb_mode = 'off'
        self.__Camera.exposure_compensation = 0
        self.__Camera.awb_gains = 1, 1
I though it should fix everything, but I can see that analog gain and digital gain change with light quantity.

**Comment by namorrellek** [comment]
dear everybody

we recently had our second solar balloon flight to the stratosphere. unfortunately the camera did't work  as planed and tested for the second time. we used the following code and got all black photos and videos during the eight hours flight - and sometimes also black files during the filling up/pre flight preparations. is there a possibility that the camera switches to a different mode when exposed to bright sunlight and snow?

here is an overview of the disaster:
https://drive.google.com/file/d/0B0iLw9bRs9SGVEV0bVdVQ0dQWVE/view?usp=sharing

any suggestions or similar experience? any help highly appreciated!

greetings from grey zurich

import picamera
import time
from datetime import datetime

count = 0
while count < 999:
with picamera.PiCamera() as camera:
camera.resolution = (2592, 1944)
time.sleep(1)
camera.start_preview()
filename = '//DATA/blue_%s_auto.jpg'%datetime.now().strftime('%Y-%m-%d-%H%M%S')
camera.capture(filename)

camera.resolution = (2592, 1944)
camera.shutter_speed = 1000
camera.exposure_mode = 'off'
camera.iso = 100
camera.awb_mode = 'sunlight'
filename = '//DATA/blue_%s_fixed.jpg'%datetime.now().strftime('%Y-%m-%d-%H%M%S')
camera.capture(filename)

camera.resolution = (1920, 1080)
camera.framerate = 25
camera.sharpness = 0
camera.contrast = -10
camera.saturation = 0
camera.ISO = 100
camera.video_stabilization = False
camera.exposure_compensation = 0
camera.exposure_mode = 'off'
time.sleep(1)
camera.start_preview()
camera.awb_mode = 'off'
camera.awb_gains = (1.45, 1.45)
camera.image_effects = 'none'
camera.color_effects = None
camera.rotation = 180
camera.hflip = False
camera.vflip = False
camera.shutter_speed = 1000
filename = '//DATA/blue_%s.h264'%datetime.now().strftime('%Y-%m-%d-%H%M%S')
camera.start_recording(filename, bitrate=25000000)
camera.wait_recording(627)
camera.stop_recording()
count = count + 1

**Comment by waveform80** [comment]
Answered comment above in #266 (please don't double post - I get notifications about *everything* both comments and new issues)

**Comment by namorrellek** [comment]
sorry. i was confused after posting as his page says "closed" in the top left part. won't happen again!

**Comment by geerlingguy** [comment]
I was having the exact same issue; added a `sleep(1)` right after setting `exposure_mode` to `off`, and it seems to fix the issue for me.
