### ISSUE TITLE
Add intra-refresh type property

### ISSUE THREAD

**Issue by waveform80** [waveform80/picamera#193]
There's a new option pending in raspivid to control intra-refresh type; not sure what that is yet, but we should have an equivalent property in picamera. See raspberrypi/userland#215 for details.

**Comment by JamesH65** [comment]
There are a number of different ways of formatting the I-frame, this gives the option to specify which one you want. Not exactly sure what some do, but cyclic rows can be used to partially send bits of an I-frame over time - which can smooth out bandwidth requirements, but with a slight compression penalty.

**Comment by waveform80** [comment]
Ah - sounds handy for streaming which is something I desperately need to write a FAQ about (the number of questions I get about streaming seems endless!)
