### ISSUE TITLE
pycamera installs in /usr/lib/python3.4/sitepackages  not /usr/lib64/...

### ISSUE THREAD

**Issue by inkblotter** [waveform80/picamera#194]
Fedora core 21 64-bit
Imagine my surprise when pycamera installed itself in the 32-bit  python3.4 site-packages when it should have installed in /usr/lib64/python3.4/site-packages.

Of course I seldom use software running at 32-bits.

**Comment by waveform80** [comment]
Can't say I've tested picamera on pidora. I'm assuming you installed it via "sudo pip install picamera"?
