### ISSUE TITLE
Version 1.10 annotate_text_size Doesn't Work

### ISSUE THREAD

**Issue by kylerichards89** [waveform80/picamera#205]

**Comment by waveform80** [comment]
I should mention for anyone else running across this ticket - annotate_text_size does require that the firmware support the MMAL ANNOTATE_V3 structure. At the time of writing I'm not sure such firmwares have made it into mainstream Raspbian (i.e. I'm not sure a straight forward "sudo apt-get update" and "sudo apt-get upgrade" will pull in a sufficiently up to date firmware).

If that's not the case, you may need to run "sudo rpi-update" to pull in a sufficiently recent firmware. Be aware that usage of "sudo rpi-update" is being "de-emphasized" generally as it's considered safer and easier to rely solely on apt-get as much as possible (to some extent, rpi-update steps on apt-get's turf by modifying files that were formerly under the control of apt-get without apt-get being aware of it). The [installation chapter](http://picamera.readthedocs.org/en/release-1.10/install2.html) for picamera now recommends usage of apt-get (as above), but also contains instructions for switching back from rpi-update to apt-get.

So, if your firmware isn't up to date enough, and apt-get upgrade hasn't pulled in a recent enough firmware (I *think* you need something on or after rev 760 or thereabouts) you've got a couple of options:

1. Wait for Raspbian's packages to include a sufficiently recent version then upgrade with apt-get as normal

2. Pull in an up to date firmware now with "sudo rpi-update" (you can always switch back to using apt-get as your firmware update mechanism by following the instructions linked above).
