### ISSUE TITLE
Typo in Changelog

### ISSUE THREAD

**Issue by darkstar007** [waveform80/picamera#206]
The release date given in the Changelog for version 1.10 is '2014-03-31' as this is somewhat before the release date for 1.9, I expect you meant '2015-03-31'!

**Comment by waveform80** [comment]
Well spotted! I'll change that in the 1.11 release (I can't change the 1.10 tag that RTD is building the 1.10 docs from without breaking things for anyone relying on it, but at least it'll be correct in future releases). I should add that the 1.11 release won't be any time soon - it so happens that the (correct) 1.10 release date was also the birthday of our first child so things are a tad busy at the moment while we adjust!
