### ISSUE TITLE
awb lock for video?

### ISSUE THREAD

**Issue by spikedrba** [waveform80/picamera#207]
Hi all,

I'm following http://picamera.readthedocs.org/en/latest/recipes1.html#capturing-consistent-images and wondering if it's ok to apply the same concept to video (attempting an outdoor security camera project).

What do you think about locking AWB/shutter speed and then releasing it every few minutes (when the camera is not recording)?

thanks,

Spike

**Comment by waveform80** [comment]
Hi Spike,

Locking AWB or shutter speed should work fine for either still captures or video recordings. Unlocking it periodically is a decent idea though, especially with something long running like a security camera, so that it can adjust to changing light conditions and such like.
