### ISSUE TITLE
High resolution image capture, during low-res motion detection

### ISSUE THREAD

**Issue by alexkreimer** [waveform80/picamera#220]
This issue is actually a follow-up for #125 

The difference in my case is that I'm trying to do low res motion detection and capture a hi-res image when the motion is detected.

I use the following code to reproduce the problem:

    import picamera
    import picamera.array
    import numpy as np

    class DetectMotion(picamera.array.PiMotionAnalysis):
    def analyse(self, a):
        global motion_detected
        a = np.sqrt(
            np.square(a['x'].astype(np.float)) +
            np.square(a['y'].astype(np.float))
            ).clip(0, 255).astype(np.uint8)
        if (a > 60).sum() > 10:
            motion_detected = True

    with picamera.PiCamera() as camera:
        with DetectMotion(camera) as output:
            camera.resolution = camera.MAX_RESOLUTION
            camera.framerate = 15
            camera.start_recording('video.h264', resize=(320, 240), motion_output=output)
            camera.wait_recording(10)
            camera.capture('foo.jpg', use_video_port=True)
            camera.wait_recording(10)
            camera.stop_recording()

This code crashes like this:

    (env)pi@raspberrypi ~/rpi-repo/rpi $ python ~/tmp/test.py 
    Traceback (most recent call last):
      File "/home/pi/tmp/test.py", line 30, in <module> camera.stop_recording()
     File "/home/pi/.virtualenvs/env/local/lib/python2.7/site-packages/picamera/camera.py", line 976, in __exit__
       self.close()
     File "/home/pi/.virtualenvs/env/local/lib/python2.7/site-packages/picamera/camera.py", line 955, in close
        self.stop_recording(splitter_port=port)
      File "/home/pi/.virtualenvs/env/local/lib/python2.7/site-packages/picamera/camera.py", line 1362, in stop_recording
       self.wait_recording(0, splitter_port)
      File "/home/pi/.virtualenvs/env/local/lib/python2.7/site-packages/picamera/camera.py", line 1333, in     wait_recording
        encoder.wait(timeout)
      File "/home/pi/.virtualenvs/env/local/lib/python2.7/site-packages/picamera/encoders.py", line 853, in wait
        raise self.exception
    ValueError: total size of new array must be unchanged

**Comment by waveform80** [comment]
The issue is that you're specifying `resize` in the `start_recording` call. The `PiMotionAnalysis` class determines the amount of data to expect based on the camera's resolution. However in this case the camera's resolution is being overridden as you've requested the output be resized to 320x240. In this case you also need to tell the analysis class what size to expect by specifying the `size` parameter in the constructor. Here's a modified version of your code:

    import picamera
    import picamera.array
    import numpy as np

    class DetectMotion(picamera.array.PiMotionAnalysis):
        def analyse(self, a):
            global motion_detected
            a = np.sqrt(
                np.square(a['x'].astype(np.float)) +
                np.square(a['y'].astype(np.float))
                ).clip(0, 255).astype(np.uint8)
            if (a > 60).sum() > 10:
                motion_detected = True

    with picamera.PiCamera() as camera:
        camera.resolution = camera.MAX_RESOLUTION
        camera.framerate = 15
        with DetectMotion(camera, size=(320, 240)) as output:
            camera.start_recording('video.h264', resize=(320, 240), motion_output=output)
            camera.wait_recording(10)
            camera.capture('foo.jpg', use_video_port=True)
            camera.wait_recording(10)
            camera.stop_recording()
