### ISSUE TITLE
1/6 Frame rate with 6 second shutter speed results in instant solid green image

### ISSUE THREAD

**Issue by pw85** [waveform80/picamera#229]
I'm trying to get a long exposure picture with the following settings.

```python
framerate = fraction(1,6)
iso = 100
shutter_speed = 6000000
exposure_mode = 'verylong'
awb_mode = 'fluorescent'
```

Raspberry Pi B
Camera Rev 1.3
picamera installed and wheezy updated on 4/7/15.

I get an image after 6 seconds (what I'm after). However, the image is solid green. By commenting out the frame rate line, I get a proper picture but it's an instant one, not the 6 seconds. Are there any conflicting or missing settings? Or does anyone have a couple of suggestions I can try?

**Comment by waveform80** [comment]
You're not missing any settings - what you're missing is an extremely long wait while AWB sorts out some decent gains for the preview; see the explanation I just wrote under #227 (with a framerate of 1/6th fps I'd expect to have to wait *minutes* for decent AWB gains - if you know what gains you want to use in advance you could specify them manually by setting `awb_mode` to off and then settings `awb_gains` accordingly).
