### ISSUE TITLE
Automatic gain control (AGC)

### ISSUE THREAD

**Issue by Flojou** [waveform80/picamera#237]
Hello I 'd like to know if I can change the gain value ( Exposure) manually
As in exmple: 

```python
 import picamera, time
  with picamera.PiCamera() as camera:
     camera.led = False 
     camera.resolution = (640,480)  
     camera.framerate = 20 
     camera.start_preview() 
     camera.start_recording(‘video.h264’, format='h264') 
	
	while continuer < 120:
		continuer =+1
                camera.gain=+5
     	camera.stop_recording() 
```

merci d avance

**Comment by waveform80** [comment]
Unfortunately not directly. As documented under the [`exposure_mode`](http://picamera.readthedocs.org/en/release-1.10/api_camera.html#picamera.camera.PiCamera.exposure_mode) property, the gains can only be fixed but not set directly. It's possible to used a loop to periodically check the gains, then fix them when they settle on (or near) desired values, but that's about as close as you can get to directly setting them.
