### ISSUE TITLE
Changing position of annotation text

### ISSUE THREAD

**Issue by myrtleTree33** [waveform80/picamera#252]
Hi, 

Is there any way to set the XY position of annotations?

Great job by the way!!

**Comment by waveform80** [comment]
Sorry, no. The firmware currently provides no means of positioning annotations (just text size and colour).

**Comment by barsznica** [comment]
Setting x,y positions would be great!
Thanks for the great work;)

**Comment by waveform80** [comment]
Sorry, not up to me - annotation is a facility provided by the firmware (picamera is just a wrapper over (some libraries which wrap) the firmware).

**Comment by barsznica** [comment]
Do you know how I could use colours other than white for something like below?

# Create an array representing an image of a cross through the center of the 
# display. The shape of the array must be of the form (height, width, color)
a = np.zeros((720, 1280, 3), dtype=np.uint8)
a[640, :, :] = 0xff
a[:, 360, :] = 0xff
