### ISSUE TITLE
Sampling H264 video at lower framerate causes faster playback

### ISSUE THREAD

**Issue by myrtleTree33** [waveform80/picamera#253]
Hello,

I am trying to sample video at 12 fps.  This is going all fine, however playback of the video shows that it goes much faster (believe that is because it is playing back at 30fps).

Is there anything I can do to force video to be played back at 12 fps always?  Thank you!

**Comment by waveform80** [comment]
The camera's H264 encoder doesn't output a full MP4 file (which would contain FPS information); instead it outputs an H264 NAL stream which just has frame-size and a few other details (but not FPS). Most players default to 24 or 30fps, hence recordings at 12fps will appear "fast". Therefore your playback client needs to be told what fps to use when playing back (assuming it supports such an option) or you need to wrap the H264 output in a full MP4 container (e.g. with MP4Box or ffmpeg).
