### ISSUE TITLE
requesting an intra frame while recording

### ISSUE THREAD

**Issue by chetanbnaik** [waveform80/picamera#257]
Hello Developers,

I want to request a key frame (intra frame) while video recording is in progress. What is the correct way of doing this?

Many thanks for answering this quite a basic question.

**Comment by waveform80** [comment]
Currently picamera doesn't provide a means for doing this via it's API but there is an MMAL call for it. Frankly, I ought to add a method for this and use it in `split_recording`. I'll mark this as a future enhancement - not sure if I can squeeze it into 1.11, but I'll try.
