### ISSUE TITLE
Annotate for several splitters

### ISSUE THREAD

**Issue by cronnosli** [waveform80/picamera#269]
There is a way to insert a annotation per splitter?

Now I'm using the annotate_text as below
`self.camera.annotate_text = '{0} {2}'.format(self.banner, dt.datetime.now().strftime(self.dtFormat))`

But I wanna to insert a identification per video recorded.

**Comment by 6by9** [comment]
Not possible within the GPU code.
You'll note that the annotation is being set on ```self.camera```, so the camera component. That is common to all output streams. There is no similar support in any other component within the firmware.

You could look at writing the annotation yourself onto image buffers pulled back to the ARM.

**Comment by waveform80** [comment]
Closing old tickets; do feel free to re-open if you've further queries about this!
