### ISSUE TITLE
Dev dependency on lsb-release and libjpeg8-dev 

### ISSUE THREAD

**Issue by eldog** [waveform80/picamera#272]
Following the development installation instructions in the documentation it appears that `make develop` fails due to `lsb-release` and `libjpeg8-dev` not being installed.

I think the system dependency installation command should be

$ sudo apt-get install build-essential git git-core exuberant-ctags \
    libjpeg8-dev lsb-release python-virtualenv

**Comment by waveform80** [comment]
Good catch :) I'll sling this into the instructions for 1.11

**Comment by eldog** [comment]
Cool : ) Also I think `python-dev` is required too.

**Comment by waveform80** [comment]
Hmm ... might be, but that's generally only needed for C-based extensions and picamera's pure python (well, sort of)

**Comment by eldog** [comment]
I think it caused `make develop` to crash when `pip` tried to install Pillow.

**Comment by waveform80** [comment]
Ah, of course - that's a dep of the test suite. Yup, that'll need to go in too.
