### ISSUE TITLE
HDR support for New Raspberry Pi Camera Board

### ISSUE THREAD

**Issue by egoist-sx** [waveform80/picamera#282]
Hi, I have noticed that new pi camera module uses sony IMX219PQ, which support ISP HDR.

I saw MMAL_PARAMETER_HIGH_DYNAMIC_RANGE in mmal parameters, but found nowhere used this variable. Is there anyway that I can utilize this new HDR functionality in pi camera?

**Comment by waveform80** [comment]
As noted in raspberrypi/userland#311 HDR isn't supported by the new camera. As for what appears in the MMAL header translation - there's plenty of functionality in MMAL which isn't baked into the Pi's version of the firmware (presumably for cost / licensing reasons) which I would assume includes the HDR stuff.

**Comment by 6by9** [comment]
Correct. HDR is not supported on either of the Pi cameras and it's extremely unlikely to ever be done.
Recommend closing this issue as "won't fix".
