### ISSUE TITLE
capture full resolution images with v2.1 and Pi3

### ISSUE THREAD

**Issue by schnarz** [waveform80/picamera#294]
Hi there, trying with

```
import RPi.GPIO as GPIO
import picamera
import time
import sys

GPIO.setmode(GPIO.BCM)
GPIO.setup(18, GPIO.IN, pull_up_down=GPIO.PUD_UP)
with picamera.PiCamera() as camera:
	while True:
		input_state = GPIO.input(18)
		if input_state == False:
			camera.framerate = 5
			camera.resolution=(3280, 2464)
			camera.preview_fullscreen=True
			camera.start_preview()
			time.sleep(2)
			camera.capture('01.jpg')
			time.sleep(1)
			camera.stop_preview()
```

to capture 3280x2464 pixels, which works fine with raspistill from the command line.

All I get is

```
$ python minimal.py
mmal: mmal_vc_port_enable: failed to enable port vc.ril.video_splitter:in:0(I420): ENOMEM
mmal: mmal_port_enable: failed to enable connected port (vc.ril.video_splitter:in:0(I420))0x5d0c60 (ENOMEM)
mmal: mmal_connection_enable: output port couldn't be enabled
Traceback (most recent call last):
  File "minimal.py", line 24, in <module>
    camera.resolution=(3280, 2464)
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 2283, in _set_resolution
    self._enable_camera()
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 732, in _enable_camera
    prefix="Failed to enable splitter connection")
  File "/usr/lib/python2.7/dist-packages/picamera/exc.py", line 191, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to enable splitter connection: Out of memory
```

If I reduce the resolution in the code to 3000x2000, for example, the procedure works.

The code runs on a Pi3. I did `rpi-update`, `rpi-upgrade` and `apt-get update`.
Am I doing something wrong?
Output preview is on a 800x480 7" Display

Thanks in advance

Jochen
_____________________________________________________________________
Update:
If I understand it correctly, version 1.10, distributed via `apt-get` does not support the full resolution of v2.1 camera. So I did some 
```
git clone git://github/waveform80/picamera.git
sudo python setup.py build
sudo python setup.py install
```
and it worked!!!

**Comment by waveform80** [comment]
> If I understand it correctly, version 1.10, distributed via apt-get does not support the full resolution of v2.1 camera.

Yup, that's correct - 1.11 will support the full resolution, but it's taking a lot longer than I expected, sorry! Given you've done a manual installation, when 1.11 is released you'll need to uninstall your manual installation because it'll take precedence over apt's installation. So, when 1.11 comes out (and Raspbian gets the new package), you'll need to do:

```bash
# (from within your cloned repo)
cd picamera
sudo python setup.py uninstall
sudo apt-get update
sudo apt-get upgrade
```

But for now, it's a decent stop-gap.
