### ISSUE TITLE
Preview fails at full resolution with V2 camera module

### ISSUE THREAD

**Issue by waveform80** [waveform80/picamera#296]
The camera's preview fails to operate correctly with a V2 module set to maximum resolution. This appears to be a hardware limitation (the failure looks similar to when too many overlays are applied), and is replicable with raspistill with the the `-fp` switch.

To mitigate we'll need to separate preview and camera resolution just as raspistill does. Check whether preview resolution can be changed without re-constructing the renderer (probably just means tweaking port formats but I'd bet the preview connection will need disabling first). Add a `resolution` parameter to `start_preview` and a similar attribute to `PiPreviewRenderer`.

**Comment by 6by9** [comment]
Yes the HVS (Hardware Video Scaler) will be underflowing when trying to do that. 5MP tends to do it too - there are too many lines of context required to produce each line of output, and whilst there are some levels of decimation, they're only vertical as there's no sensible way to skip pixels horizontally when reading bursts from RAM.

TBH the -fp option of raspistill etc should probably be deprecated - I think it only had a real use when we had different FOVs between preview and stills resolutions.
