### ISSUE TITLE
TypeError: 'MMALBuffer' object does not support indexing

### ISSUE THREAD

**Issue by Berryfier** [waveform80/picamera#337]
I am running a strobe synchroniser which relies on the comparison of presentation and system time stamps. The method of obtaining the presentation time stamp is based on the example recipe which extends the Custom Encoder PiCookedVideoEncoder class; in my case using pts in place of flags. Under
def _callback_write(self, buf):
the recipe has
        (buf[0].flags 
Whilst this worked in version 1.10, version 1.12 reports
TypeError: 'MMALBuffer' object does not support indexing
sys.excepthook is missing
lost sys.stderr
With guidance from the interactive help, the error can be overcome by making these changes
def _callback_write(self, buf, key=0):
        (buf.flags 
Thank you for publishing the recipies.

**Comment by waveform80** [comment]
Ah, many thanks! I'll get that fixed up for the next version.
