### ISSUE TITLE
libmmal.so dependency not checked by installer

### ISSUE THREAD

**Issue by polycopter** [waveform80/picamera#340]
Installed /usr/lib/python2.7/site-packages/picamera-1.12-py2.7.egg
Processing dependencies for picamera==1.12
Finished processing dependencies for picamera==1.12
[prompt]$ python
Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import picamera
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "picamera/**init**.py", line 72, in <module>
> > >     from picamera.exc import (
> > >   File "picamera/exc.py", line 41, in <module>
> > >     import picamera.mmal as mmal
> > >   File "picamera/mmal.py", line 47, in <module>
> > >     _lib = ct.CDLL('libmmal.so')
> > >   File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in **init**
> > >     self._handle = _dlopen(self._name, mode)
> > > OSError: libmmal.so: cannot open shared object file: No such file or directory

**Comment by stuaxo** [comment]
I hit the same thing in installing with pip in a virtualenv on python3.5

**Comment by waveform80** [comment]
There's no (simple) way that I'm aware of to enforce / check that dependency with Python's packaging system. The deb package, however, *does* enforce that dependency by depending on the `libraspberrypi0` package which is what includes `libmmal.so`. I could add a note to the pip installation instructions, but I think that's about all I can do (I've no idea what package includes `libmmal.so`, and the associated libraries, on distros other than Raspbian).

**Comment by stuaxo** [comment]
Makes sense, I was trying to run this on a PC which didn't work obviously :)

**Comment by waveform80** [comment]
On a PC? Err, yeah, never gonna work there ;)

**Comment by stuaxo** [comment]
I was using pi3d (which does work there) + sort of stopped thinking when I went to install requirements for some of the examples :)

**Comment by polycopter** [comment]
I also was trying to install on a non-Pi device (PC, I think); I never
realized this was RPi-specific. Sorry!

**Comment by waveform80** [comment]
Okay, there's evidently enough people trying to install this on PCs (?!) that I could make things a little more obvious for them. I'll throw some stuff in `setup.py` to throw an error if install is being attempted on something that's blatantly not a Pi (however, I'll deliberately only do this for the "install" command - there's good reasons for development installations on non-Pi platforms, e.g. building docs, packages, etc.)

**Comment by stuaxo** [comment]
Thanks :)
