### ISSUE TITLE
capture of a jpeg with resize and splitter port to a stream fails

### ISSUE THREAD

**Issue by dneunkirch** [waveform80/picamera#344]
In my script for motion detection fails the capture method (https://github.com/dneunkirch/motiondetection/blob/testing/python/motion_detection.py#L176) not reproducible (invoked successful over 10000 times).

```python:
stream = io.BytesIO()
camera.capture(stream, format='jpeg', resize=(192, 108), splitter_port=3, use_video_port=True)
```
```
File "build/bdist.linux-armv6l/egg/picamera/camera.py", line 1383, in capture
     encoder.start(output)
File "build/bdist.linux-armv6l/egg/picamera/encoders.py", line 1024, in start
     super(PiCookedOneImageEncoder, self).start(output)
File "build/bdist.linux-armv6l/egg/picamera/encoders.py", line 395, in start
     self.parent._start_capture(self.camera_port)
File "build/bdist.linux-armv6l/egg/picamera/camera.py", line 503, in _start_capture
     len([e for e in self._encoders.values() if e.active]) == 1):
File "build/bdist.linux-armv6l/egg/picamera/encoders.py", line 376, in active
     return bool(self.output_port and self.output_port.enabled)

AttributeError: 'NoneType' object has no attribute 'enabled'
```
environment:
- picamera version 1.12 (master) 
- camera board v1
- on different raspberries:
 - 4.4.20-v7+ #908 SMP Wed Sep 7 14:44:27 BST 2016 armv7l GNU/Linux
 - 4.4.20+ #908 Wed Sep 7 14:35:04 BST 2016 armv6l GNU/Linux
 - 4.4.20-v7+ #909 SMP Tue Sep 13 16:59:08 BST 2016 armv7l GNU/Linux

I'm sorry that I don't have more informations.

**Edit**
I got just an other error (also thrown at the capture method):
```
File "build/bdist.linux-armv6l/egg/picamera/camera.py", line 1388, in capture
    'Timed out waiting for capture to end')

PiCameraRuntimeError: Timed out waiting for capture to end
```

**Comment by waveform80** [comment]
Hmm, that's a race condition (which is why it's showing up extremely rarely). I'll see what I can do about getting that fixed in 1.13
