### ISSUE TITLE
JPEG restart interval

### ISSUE THREAD

**Issue by waveform80** [waveform80/picamera#369]
Missed `--restart` getting added to raspistill a few months back. Should add a similar parameter to the capture methods.

**Comment by pirquessa** [comment]
What the point of this attribute ?

**Comment by waveform80** [comment]
Essentially increased redundancy in the JPEG (useful when transmitting the results over a connection that's likely to drop bits). The [associated thread](https://www.raspberrypi.org/forums/viewtopic.php?f=38&t=153553) has a bit more info

**Comment by pirquessa** [comment]
Outch, ok ;)
