### ISSUE TITLE
picamera error on Model A

### ISSUE THREAD

**Issue by martinohanlon** [waveform80/picamera#38]
Hi,

I'm getting an error when I try and execute some picamera code on a Model A.  I've developed some software on a model b and it works fine.  I have come to run this on a model a and I keep getting the same error when instantiating picamera.Camera().

<pre>
mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
Unexpected error -  <class 'picamera.exc.PiCameraError'> Camera component couldn't be enabled: Out of resources (other than memory)
Traceback (most recent call last):
  File "/home/pi/dev/pelmetcam/pelmetcam.py", line 230, in <module>
    with picamera.PiCamera(False) as camera:
  File "/home/pi/dev/picamera/picamera/camera.py", line 239, in __init__
    self._init_camera()
  File "/home/pi/dev/picamera/picamera/camera.py", line 329, in _init_camera
    prefix="Camera component couldn't be enabled")
  File "/home/pi/dev/picamera/picamera/exc.py", line 102, in mmal_check
    }.get(status, "Unknown status error")))
picamera.exc.PiCameraError: Camera component couldn't be enabled: Out of resources (other than memory)
</pre>

Its exactly the same setup, the same sd card, everything.  I've rebuilt the sd card from a new raspbian image, always with the same result, its runs fine on my model b, but I execute it on model a and it fails.  I've done an apt-get update, upgrade and rpi-update but with no joy.

The model b is a 256Mb Rev 1, while the model a is a 256Mb Rev 2.  Other than the rev difference, they are virtually identical.

Im not entirely convinced this is an error with picamera specifically but the error is being generated from picamera.Camera() so I though I'd see if you had any ideas!  I have run a couple of the picamera test programs on the model a and they are fine, but when run within my code it always fails.

Any ideas?

Thanks

Martin

**Comment by Manoj-nathwani** [comment]
For anyone who stumbles across this trying to find another solution...

# Solution
Only initialize the `picamera.PiCamera()` object once, then re-use it to make more pictures. So taking it out the `while True` loop and making it reusable solved the problem in my case 😊
