### ISSUE TITLE
numpy getbuffer deprication in comments

### ISSUE THREAD

**Issue by sundryseth** [waveform80/picamera#457]
Numpy deprecated getbuffer() and the example in the document does not work.

Found this line in the second half of this in the documentation.
https://picamera.readthedocs.io/en/release-1.13/recipes1.html#overlaying-images-on-the-preview

o = camera.add_overlay(np.getbuffer(a), layer=3, alpha=64)
I think it should be
o = camera.add_overlay(a.tobytes(), layer=3, alpha=64)

I chose to use tobytes because the source down below says tobytes is the fastest.
I have no data for picamera usage though.

Sources:
https://stackoverflow.com/questions/21821045/numpy-getbuffer-causes-attributeerror-module-object-has-no-attribute-getbuff

**Comment by waveform80** [comment]
Thanks - that definitely needs updating; I'll get it done for 1.14
