### ISSUE TITLE
Bayer data handling has the LSBits reversed

### ISSUE THREAD

**Issue by 6by9** [waveform80/picamera#462]
In https://github.com/waveform80/picamera/blob/master/docs/examples/bayer_data.py#L55 when describing the 2 least sig bits from the 4 pixels, the order is reversed.
The correct order is:
```
#  byte 1   byte 2   byte 3   byte 4   byte 5
# AAAAAAAA BBBBBBBB CCCCCCCC DDDDDDDD DDCCBBAA
```
as confirmed by https://linuxtv.org/downloads/v4l-dvb-apis-new/uapi/v4l/pixfmt-srggb10p.html or the CSI-2 spec.

**Comment by waveform80** [comment]
Doh - well spotted! I'll get that fixed in 1.14
