### ISSUE TITLE
be able to set analog and digital gain control api

### ISSUE THREAD

**Issue by GeneGIGA** [waveform80/picamera#468]
This is really a feature request to allow control of the analog_gain and digital_gain setting. This for us is needed, because of the following scenario...

We have a timelapse and imaging device setup where we need really consistent images. If the pi reboots, we want to be able to 'zero' out the settings so that a set of images taken days ago will match up with images taken on another day.

Right now, we can manually set the exposure_mode to 'off', shutter_speed, awb_gains to 'off' to control the exposure nicely. BUT...when the camera is initialized, the default is exposure_mode = 'auto' and it automatically adjusts the analog and digital gain. Once we turn exposure_mode = 'off', we have to live with whatever the analog and digital gain are set to...which varies. 

We can get around this by controlling the lighting environment when the picamera starts up...but it would make it soooooo much easier if we could manually set the analog_gain and digital_gain ourselves.

Thanks!

**Comment by waveform80** [comment]
Nothing I can do about this, I'm afraid. The picamera library is a thin(ish) wrapper over the MMAL interface to the camera; if that layer doesn't provide such a facility (and last time I checked, admittedly a while ago, it didn't) there's nothing I can do about it.
