### ISSUE TITLE
v2 camera identifying as 'RP_OV5647' 

### ISSUE THREAD

**Issue by michelprog** [waveform80/picamera#469]
I use 6by9's modified dcraw program to convert the camera output.

In v1.10 this worked, but now that i installed 1.13, it doesn't recognize the raw data anymore ('Cannot decode file...')
I tracked this down to picamera saving RP_OV5647 as camera model instead of RP_imx...

I can work around this, but it might be a nuisance to other users.

**Comment by waveform80** [comment]
Where exactly did you track this down to? The raw output itself? I'm not sure what could be going wrong here given that picamera just writes out what it gets from the firmware (including for raw output), hence I'm afraid without some more detail I can't really do much with this. Feel free to re-open the issue if you've got some example code I could use to replicate the issue.
