### ISSUE TITLE
the camera picamera doesn't work after have close VideoStream(usePicamera=true.... ( by vs.stop) and then have open new resource to take video ( by with picamera.Picamera() as camera: ) 

### ISSUE THREAD

**Issue by LorrainBreton** [waveform80/picamera#474]
Hello Dave,

Adrian Rosebrock (Chief PyImageSearcher) told me to solicit you to solve the problem that I explained to him below.

Could you help me to solve this problem ?

Thanks in advance

Claude
----------------------------------------------------------------
Hello Adrian,

Thank you for your post. 

https://www.pyimagesearch.com/2018/02/19/real-time-object-detection-on-the-raspberry-pi-with-the-movidius-ncs/

I followed your 2 post in detail

1)	Getting started with the Intel Movidius Neural Compute Stick
2)	Real-time object detection on the Raspberry Pi with the Movidius NCS

I own a RPI3, a picamera V2 camera, a 32GB SD card, with the MOVIDIUS intel module.

I followed your post in detail and installed the example you give (ncs_realtime_objectdetection.py). 

Everything is working properly and thank you very much.

However, I would like help on the following problem:

From your example, I completed it to use the RPI 3 + Movidius to make a surveillance camera to detect only  the presence of people. 
( my software is cr2_GB_ncs_realtime_objectdetection.py)

- My software also works correctly when i don't use the possibility to take a video when personn is detected. 
- But, this software doesn't work properly with to take video. ( see code below). In fact, the software works correctly 
on a few loops (it can be 1 or 2 or 3 or more ( its occurence is random), then it comes out in error. 
(with error: picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources )(see my log below ).

note: 
1) but I was careful in the software to stop the videostream routine before launching the video routine when there detection of a human person. 

2) I read in Picamera 1.13 Documentation, chapter "Out of resources on V2 module." I have increasing gpu_mem in /boot/config.txt (from 128 to 256).

3) version picamera used: 1.13  . version imutils: 0.4.5 version numpy:1.14.1

Could you help me to solve this problem ?

Thanks in advance
Claude

See enclosed : 
1)  my script cr2_GB_ncs_realtime_objectdetection.py
2)  the log file seeing the "out of resource" error
[cr2_GB__ncs_realtime_objectdetection.docx](https://github.com/waveform80/picamera/files/1815425/cr2_GB__ncs_realtime_objectdetection.docx)
[cr_gb_ncs.log](https://github.com/waveform80/picamera/files/1815426/cr_gb_ncs.log)

**Comment by waveform80** [comment]
Sorry, there's no way I can dig into a script this large, especially without all the dependencies. If you can come up with a *minimal* reproduction case I can take a look but as it stands this is way too large and involved.
