### ISSUE TITLE
PiCameraCircularIO only records 1 second regardless of how many specified

### ISSUE THREAD

**Issue by Esser50K** [waveform80/picamera#496]
So I tried doing some tests with the split recording feature and came up with this little script:

```python
import io
import picamera

camera = picamera.PiCamera(resolution = "1280x720", framerate = 30)
before_buffer = picamera.PiCameraCircularIO(camera, seconds = 5)
camera.start_recording(before_buffer, format="h264", quality = 10)
camera.wait_recording(5)
outfile = io.open("test.h264", "wb", buffering = 1048576)
before_buffer.copy_to(outfile, seconds = 5)
before_buffer.clear()
camera.split_recording(outfile)
camera.wait_recording(5)
camera.stop_recording()
outfile.close()
```

I would think this script would produce a 10 second video. However I produces a six second video.

I've tried exiting just after writing the the contents of the CircularBuffer to the file and that produced a 1 second video.

What am I doing wrong? Or is there a bug in the library?

**Comment by Esser420** [comment]
I just realised this happens because I'm changing the "quality" parameter in start_recording. If I use the default 20 it records fine

**Comment by waveform80** [comment]
Hmm, quality=10 is a very high quality but I'm still surprised it's only managing to keep 1 second in the circular buffer at that level. The bitrate should still be clamped which *should* mean the circular buffer should be capable of holding the requested 5 seconds. I realize you've worked around this, but I'll mark this as a bug to have a quick look during 1.14 as something doesn't feel right here...

**Comment by Esser420** [comment]
Oh I just saw you're thinking about making a new release! Awesome! Looking forward for it!

Got a project that highly depends on this library. Need any manpower on this?

**Comment by Esser50K** [comment]
@dbbnrl There is!
