### ISSUE TITLE
Install old version

### ISSUE THREAD

**Issue by jul1792** [waveform80/picamera#497]
Hi there,
I would like to install version 1.10 because a photobooth programme I want to run only works with this older version. Right now I am on version 1.13. how do I downgrade to 1.10? 
Thanks a lot!

**Comment by waveform80** [comment]
Quite easy; just: pip install picamera==1.10 (you may require sudo if you're installing system-wide rather than within a virtualenv). Just for reference, I never remove versions from PyPI; even if the docs aren't listed - I do prune those - all versions back to 0.3 should be available for install).
