### ISSUE TITLE
Stop and start stream

### ISSUE THREAD

**Issue by Mungbeanz** [waveform80/picamera#499]
I was just using the script from [Picamera webpage](https://picamera.readthedocs.io/en/release-1.13/recipes2.html#web-streaming)

I was wanting to know if there is a simple way to add buttons to the mini webpage to stop and start the camera?

Thanks,

**Comment by waveform80** [comment]
Rather depends what you mean by "simple" ;) For an example of interactive usage, you might want to have a look at the pantilthat branch of [pistreaming](https://github.com/waveform80/pistreaming/tree/pantilthat) which includes controls on the page for manipulating a camera attached to [pimoroni's Pan/Tilt HAT](https://shop.pimoroni.com/products/pan-tilt-hat). The code's quite a bit more involved than the simple web streaming demo, but it should give you an idea of how to add more controls.
