### ISSUE TITLE
Using splitter_port != 1 with picamera.PiCameraCircularIO not working?

### ISSUE THREAD

**Issue by pootle** [waveform80/picamera#503]
I'm having a play with multiple feeds out of the pi camera using splitter_port, and I'm having a problem when I use splitter_port with circular IO

With splitter_port unused or splitter_port = 1 all is well

But with splitter_port = 0, 2 or 3 before.h264 is always 0 bytes.

seems slightly bizarre, or am I missing something?

Here is a tweaked version of the code from the docs here:
`
import io
import random
import picamera

with picamera.PiCamera() as camera:
    camera.resolution = (1280, 720)
    stream = picamera.PiCameraCircularIO(camera, seconds=10)
    skwarg={}
    skwarg={'splitter_port':1}
    camera.start_recording(stream, format='h264', **skwarg)
    try:
        if True:
            camera.wait_recording(12, **skwarg)
            if True:
                print('Motion detected!')
                # As soon as we detect motion, split the recording to
                # record the frames "after" motion
                camera.split_recording('after.h264', **skwarg)
                # Write the 10 seconds "before" motion to disk as well
                stream.copy_to('before.h264')
                stream.clear()
                # Wait until motion is no longer detected, then split
                # recording back to the in-memory circular buffer
                camera.wait_recording(8, **skwarg)
                print('Motion stopped!')
                camera.split_recording(stream, **skwarg)
                camera.wait_recording(5, **skwarg)
    finally:
        camera.stop_recording(**skwarg)
`

**Comment by waveform80** [comment]
You need to tell the circular buffer the splitter port too, e.g.:

```python
stream = picamera.PiCameraCircularIO(camera, seconds=10, splitter_port=2)
```

This is a big hacky, but necessary as the circular buffer needs to query the encoder to find out when each frame completes; it can only find the encoder if it knows which splitter port it's on. See [docs for PiCameraCircularIO](https://picamera.readthedocs.io/en/release-1.13/api_streams.html#picameracirculario) for more info.
