### ISSUE TITLE
Add ability to capture raw camera data

### ISSUE THREAD

**Issue by waveform80** [waveform80/picamera#52]
Picamera's current "raw" capture capabilities only extend as far as outputting raw YUV or RGB data (i.e. the same thing raspistillyuv does), not the equivalent of raspistill -raw (which outputs a JPEG along with "truly" raw data from the camera prior to various bits of processing being performed). There's apparently some interest in getting access to "true" raw output and it doesn't look difficult so this should be added for the next release.

Need to consider the best method of doing this though: are people interested in JPEG+raw output (as with raspistill -raw) or do they just care about the raw bit (in which case it's a waste of time outputting the JPEG).

**Comment by thatneat** [comment]
If anyone's interested in an implementation of this (access to the raw data as a numpy array, as well as a simple demosaic to RGB) in a library that does not require the presence of camera hardware, check out my team's fork: https://github.com/OsmoSystems/picamraw/
