### ISSUE TITLE
Is it possible to have the PiPreviewRenderer display in grayscale?

### ISSUE THREAD

**Issue by kkotowick** [waveform80/picamera#560]
I'm using the Pi Camera V2. I'd like the preview overlay to show the image in grayscale instead of in color. Is this possible?

**Comment by 6by9** [comment]
Not easily. However you can request the camera produces greyscale via color_effects - https://picamera.readthedocs.io/en/latest/api_camera.html#picamera.PiCamera.color_effects

**Comment by kkotowick** [comment]
That works, thanks!
