### ISSUE TITLE
Flexible Picamera.rotation value

### ISSUE THREAD

**Issue by MCYBA** [waveform80/picamera#592]
Thanks for all this work.
I have trouble with `PiCamera.rotation`. I need to use this variable with values that are not multiples of ninety.

Seems in the PiCamera class the `rotation` enforced to be multiples of ninety. Could you provide a way to use this with more flexible angles?

best regards.

**Comment by 6by9** [comment]
No.

The processing pipe supports the basic operations of transpose (reflect in x=y), horizontal flip, and vertical flip. These allow you to do all variations of 90 degree rotations, with and without reflection.

There is no hardware within the imaging pipe that allows more complex rotations to be performed.

**Comment by MCYBA** [comment]
Got it, thanks for the reply
