### ISSUE TITLE
libmmal.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by harshavardhannarla** [waveform80/picamera#716]
Iam unable to import picamera module , It is giving error :libmmal.so: cannot open shared object file: No such file or directory

Rasberry pi 3b+ with 64bit rasberry pi os

**Comment by XPbIM3** [comment]
Same with me.
-Raspberry Pi 4B 4Gb
-64Bit rasp os
-libmmal.so is present in /opt/vc/lib/libmmal.so but seem to be a 32bit binary

**Comment by 6by9** [comment]
MMAL (which picamera uses) is not supported on 64bit userland
https://github.com/raspberrypi/userland/issues/688

**Comment by DUCHUAN99** [comment]
I use a 32bit operating system on raspberry 3b+ and still encounter the above error, what should I do?

**Comment by Swarkin** [comment]
I have the same issue on 32bit raspberry pi model b

**Comment by VisheshSingh1** [comment]
did you guys got any solution .. I am getting same error .. using model 3 b os 32bit

**Comment by Liuss44** [comment]
I had same error and I solved it by moving

> /opt/vc/lib/libmmal_vc_client.so
> /opt/vc/lib/libmmal_util.so
> /opt/vc/lib/libmmal_core.so
> /opt/vc/lib/libmmal_components.so
> /opt/vc/lib/libmmal.so

into 

> /usr/lib/


If it cant find any other files just use
`sudo find / -name "name of the file"`
and move then into >  /usr/lib/ 

worked for me

hope this helps. :)
