### ISSUE TITLE
stereo mode: how to switch camera sides

### ISSUE THREAD

**Issue by jds1993cologne** [waveform80/picamera#734]
Is it possible to witch the camera possissions in stereo mode?

**Comment by 6by9** [comment]
Memory says that if you select camera 1 (```camera_num=1``` when you [create the camera object](https://picamera.readthedocs.io/en/release-1.13/api_camera.html#picamera)) then it will swap the two camera modules over.

**Comment by jds1993cologne** [comment]
works fine, thanks a lot
