### ISSUE TITLE
Confusing error when camera isn't enabled in firmware

### ISSUE THREAD

**Issue by lurch** [waveform80/picamera#89]
If I don't run raspi-config to select the "Enable Camera" option, when I try running raspistill it provides the helpful error message:

```
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
mmal: Failed to create camera component
mmal: main: Failed to create camera component
mmal: Camera is not enabled in this build. Try running "sudo raspi-config" and ensure that "camera" has been enabled
```

However in python if I do

``` python
import picamera
camera = picamera.PiCamera()
```

it displays:

```
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 298, in __init__
    self._init_camera()
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 329, in _init_camera
    prefix="Failed to create camera component")
  File "/usr/lib/python2.7/dist-packages/picamera/exc.py", line 112, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to create camera component: Out of memory
```

Maybe picamera could also display a 'helpful' error message, rather the 'cryptic' "Out of memory" ?

**Comment by lxg2015** [comment]
i also meet such a question, it's caused by low power

**Comment by waveform80** [comment]
@lxg2015 it's not caused by low power. The most common cause is simply that the camera isn't enabled. There are other causes (deliberately setting the GPU memory split too low, or not enough free VC mem due to other processes / crashed processes) but not low power.

**Comment by JWTappert** [comment]
@waveform80 I definitely have the camera enabled but I am still getting this error. Do you have any suggestions on how I could diagnose those other issues you mentioned?

**Comment by eagleEggs** [comment]
Also having this issue currently

**Comment by eagleEggs** [comment]
Actually it only had to do with plugging into the wrong spot. All good now.

**Comment by geerlingguy** [comment]
Another possibility—if you're like me and you're using the Pi headless, you might be tempted to set the memory split to 16 MB, since you don't think you'll need the GPU for UI interactions.

The camera subsystem seems to also use the GPU, however, so you should leave it at the default—at least `64` (you can change it headless using `sudo raspi-config`).

**Comment by waveform80** [comment]
> The camera subsystem seems to also use the GPU, however, so you should leave it at the default—at least 64 (you can change it headless using sudo raspi-config).

Correct; the camera firmware is (almost?) entirely on the GPU (see the [Camera hardware](https://picamera.readthedocs.io/en/release-1.13/fov.html) chapter for more details). I think 64Mb is the bare minimum for camera usage, but that may not be enough for all operations (e.g. multiple encoders running simultaneously, higher resolutions, etc).

**Comment by j-suhas** [comment]
Plugging it into the right slot in the right direction solved my problem. 😜 I was playing around with it for 2hrs and just realized.
